:PROPERTIES:
:ID:       1c6af261-1802-4068-9c8a-f223ca7928a6
:END:
#+title: logic complex expressions
#+date: [2024-09-17 Tue 15:11]
#+description: Заметки к  лекции
#+latex_class: article
#+latex_class_options: [letterpaper]
#+latex_header: \usepackage{fontspec}
#+latex_header: \setmainfont[Ligatures=TeX]{CMU Serif}
#+latex_header: \usepackage{bookmark}
#+latex_header: \usepackage{amssymb}
#+latex_header: \usepackage{amsmath}
#+latex_header: \setlength{\parindent}{0pt}
#+options: toc:t
#+lanugage: ru
#+latex_compiler: xelatex

Многое совпадает с [[id:bbcdfb12-2081-447d-9571-8c9fa188326e][матаном]].

* Contents :toc:noexport:
- [[#модальность][Модальность]]
- [[#операции][Операции]]
  - [[#отрицание][Отрицание]]
  - [[#конъюкция][Конъюкция]]
  - [[#дизъюнкция][Дизъюнкция]]
  - [[#исключающее-разделительное-или][Исключающее (разделительное) или]]
  - [[#импликация][Импликация]]
  - [[#эквиваленция][Эквиваленция]]
- [[#условности][Условности]]
  - [[#самореферендые][Самореферендые]]
- [[#формулы][Формулы]]
  - [[#определение][Определение]]
  - [[#порядок-действий-без-скобок][Порядок действий (без скобок)]]
  - [[#подформула][Подформула]]
- [[#интерпритация][Интерпритация]]
- [[#пример][Пример]]
- [[#выполнимость][Выполнимость]]
  - [[#самые-важные-тавтологии][Самые важные тавтологии]]

* Модальность
"Гром гремит" - без модальности

"По словам Васи гром гремит" - с модальностью

* Операции
** Отрицание
Утверждение $\neg{a}$ истинно тогда и только тогда, когда $a$ - ложно; и ложно в противном случае.

** Конъюкция
Утверждение $a \land b$ истинно только в том случае, когда истинны как $a$ так и $b$.

$a \land b = b \land a$, /но только если $a$ не зависит от $b$/.

** Дизъюнкция
Утверждение $a \lor b$ истинно только в том случае, если истинны хотя бы $a$ или $b$.

** Исключающее (разделительное) или
Утверждение $a \oplus b$ истинно только в том случае, если истинно ровно одно из $a$ и $b$.

** Импликация
Утверждение $a \rightarrow b$ ложно только в том случае, если $a$ истинно и $b$ ложно; и истинно во всех остальных случаях.

** Эквиваленция
$x \leftrightarrow y$

* Условности
** Самореферендые
Например про пинокио.

* Формулы
** Определение
Формула определяется следующими правилами.

1. Каждая переменная есть формула.
2. Если $A$ - формула, то $\neg{A}$ тоже формула.
3. Если $A$, $B$ - формулы, то $A \square B$ тоже формула.

** Порядок действий (без скобок)
1. Отрицание
2. Конъюкция
3. Дизъюнкция
4. Импликация
5. Эквиваленция

** Подформула
Определяется:

1. Подформула переменной является только она сама.
2. Подформулой $\neg{A}$ являются $\neg{A}, A$ и все подформулы $A$
3. Подформулой формулы $A \square B$ являются $A \square B, A, B$ и все их подформулы.

* Интерпритация
Интерпритация это типо какая-то абстракиця со значеним T/F.
И к ней что-то приводит.

Интерпретация может меняться от окружения к окружению.
Поэтому *нельзя* просто написать "A равно T/F".

Называется любое отображение $\phi \in P \rightarrow {T, F}$

$\phi \in F \rightarrow {T, F}$

$\rightarrow$ - отображение (типо сопоставление)

$P$ - счетное множество всех переменных

$F$ - множество всех формул заданных рекурсивно

* Пример
$A = \neg{((x \lor (\neg{y} \rightarrow x)) \rightarrow \neg{y})}$

$\phi(x) = F; \phi(y) = T$

* Выполнимость
Формула называется выполнимой, если существует интерпретация, в которой эта формула истинна.

Формула называется опровержимой, если существует интерпретация, в которой эта формула ложна.

Формула называется тавтологией или (тождественно истинной), если формула истинна во всех интепретацией.

Формула называется противоречием или (тождественно ложной), если формула ложна во всех интепретацией.

** Самые важные тавтологии
*** TODO from screenshots
