:PROPERTIES:
:ID:       62ba348b-b2d1-44b7-b277-806535baa7f5
:END:
#+title: logic conclusion
#+latex_class: article
#+latex_class_options: [letterpaper]
#+latex_header: \usepackage{fontspec}
#+latex_header: \setmainfont[Ligatures=TeX]{CMU Serif}
#+options: toc:t
#+lanugage: ru
#+latex_compiler: xelatex

* Дедукция
#+begin_quote
Все марсиане имеют деревянные ноги, Геракл - марсианин, следовательно у Геракла деревянные ноги.
Все люди смертны, Сократ - человек, следовательно Сократ смертен.
#+end_quote

общее -> частное
предпосылки -> вывод

"Все люди смертны" + "Сократ - человек" = "Сократ смертен"

Истинность предпосылок не гарантирует истинного вывода.

Змеи едят яйца
Девочки едят яйца

Девочки - змеи

Все A суть Б
С есть A / C суть Б

* Индукция
#+begin_quote
Этот лебедь белый, тот лебедь белый, значит все лебеди белые
#+end_quote

много частных -> общее

* Парадокс
** Определение
Это рассуждени либо высказывание, в котором пользуясь средствами, не выходящими за рамки логики, приходят к заведомо неприемлимому результату (обычно противоречие).

** Примеры
+ Я лжец
+ Об Ахилесе и черепахе от Зиона
+ Крокодила

*** Парадокс Греллинга
Все прилагательные делятся на 2 множества.
Самодескриптивные - те, которые описывают сами себя и остальные - несамодескриптивные.

Например трудновыговариваемое. Какому множеству принадлжеит несамодескриптивное?

*** Парадокс Реви
Наименьшее натуральное число, которое нельзя описать менее чем 11 словами.

* Софизм
(с греч. Выдумка, Уловка)
** Определение
Мнимое доказательство, в котором обоснованность рассуждения пораждается чисто субъективным впечатлением, вызванным недостаточностью логического или семантического анализа.

* Задача
Две шкатулки - золотая и серебряная с надписями: Только 1 высказывание истинно и Партрет не в этой соответственно.

Нужно было понять, что без информации об истинности или ложности любой из этих надписей, невозможно прийти к выводу -> портрет может находиться где угодно.

Тоесть не обязательно, что надписи являются высказываниями.
