:PROPERTIES:
:ID:       58d818e7-ad9d-4133-89d7-a36a984d260b
:END:
#+title: logic formulas
#+date: [2024-09-18 Wed 16:58]
#+description: Заметки к  лекции
#+latex_class: article
#+latex_class_options: [letterpaper]
#+latex_header: \usepackage{fontspec}
#+latex_header: \setmainfont[Ligatures=TeX]{CMU Serif}
#+latex_header: \usepackage{bookmark}
#+latex_header: \usepackage{amssymb}
#+latex_header: \usepackage{amsmath}
#+latex_header: \setlength{\parindent}{0pt}
#+options: toc:t \n:t
#+lanugage: ru
#+latex_compiler: xelatex

* Contents :toc:noexport:
- [[#from-galery][from galery]]
- [[#что-то][что-то]]
  - [[#основные-равносильности][Основные равносильности]]
  - [[#равносильные][Равносильные]]
  - [[#теорема-о-подстановках][Теорема о подстановках]]
  - [[#штрих-шеффера][Штрих Шеффера]]
  - [[#стрелка-пирса][Стрелка Пирса]]
- [[#двойственность][Двойственность]]
- [[#фф][фф]]
- [[#пусть][Пусть]]
  - [[#пример][Пример]]
- [[#совершенность][Совершенность]]
  - [[#idea-доказать][IDEA доказать]]
- [[#приведение-к-снф][Приведение к СНФ:]]
  - [[#тождественные-преобразования][Тождественные преобразования]]
  - [[#таблица-истинности][Таблица истинности]]
- [[#проблема-разрешимости][Проблема разрешимости]]
  - [[#критерий-тождественной][Критерий тождественной]]
  - [[#][...]]
- [[#логическое-следование][Логическое следование]]
  - [[#свойства][Свойства]]
  - [[#правила-логических-умозаключений][Правила логических умозаключений]]
  - [[#проверка][Проверка]]

* что-то
$F \equiv H \iff \phi(F(x_1, x_2, \ldots, x_n)) = \phi(H(x_1, x_2, \ldots, x_n))$

Две формулы F и H тогда и только тогда, когда формула $F \iff H$ есть тавтология.

Следовательно
отношение равносильности между формулами есть отношение эквивалентности.

** Основные равносильности
$A \leftrightarrow B \equiv (A \rightarrow B) \land (B \rightarrow A) \equiv (A \land B) \lor (\overline{A} \land \overline{B})$
$A \rightarrow B \equiv \overline{A} \lor B \equiv \overline{A \land \overline{B}}$
$A \rightarrow B \equiv \overline{B} \rightarrow \overline{A}$
$A \land B \equiv \overline{A \rightarrow \overline{B}} \equiv \overline{\overline{A}\lor \overline{B}}$

** Равносильные
let $A \equiv B$

$\overline{A} \equiv \overline{B}$
$A \land B \equiv B \land C$
$A \lor B \equiv B \lor C$

$A \rightarrow C \equiv B \rightarrow C$
$C \rightarrow A = C \rightarrow B$
$A \leftrightarrow C = B \leftrightarrow C$

** Теорема о подстановках
$C_A$ - формула, содержащая в качестве своей подформулы формулу $A$.
Пусть $C_B$ получается из $C_A$ заменой формулы $A$
в этом вхождении на $B$. Тогда, если $A \equiv B$, то $C_A \equiv C_B$

$C$ - формула, содержащая в которой выделено
одно вхождение переменной $V$.
Пусть $C_X, C_Y$ получается из $C$ заменой переменной $V$ на $X, Y$
соответственно. Тогда, если $X \equiv Y$, то $C_X \equiv C_Y$

Всякую формулу алгебры можно заменить равносильной ей формулой, содержащей только логический операции конъюнкции, дизъюнкции и отрицания.

** Штрих Шеффера
$x \uparrow y = \overline{x \land y}$

** Стрелка Пирса
$x \downarrow y \equiv \overline{x \lor b}$

* Двойственность
Символы $\land, \lor$ называются двойственными друг другу.

Формула называется двойственной другой, если все операции заменили на двойственные.

Двойственный список - инвертированный по значениям список.

* фф
Пусть $A(x_i)$ - формула, $<s_i>$ - список истинности её переменных.
Тогда $A(s_i) \equiv T \iff A^* \equiv F$ на списке $<t_i>$ двойственном к $<s_i>$

Приницп двойственности: $A \equiv B \Rightarrow A^* \equiv B^*$.

Можно использовать для нахождения новых равносильностей.

$X \land (Y \lor Z) \equiv (X \land Y) \lor (Z \land Z) \Rightarrow X \lor (Y \land Z) \equiv (X \lor Y) \land (Z \lor Z)$

* Пусть
$x_1, x_2, \ldots, x_n$ - элементарные высказывания

Формула алгебры логики - функция входящих в нее элементарных выссказываний

$A(x_1, x_2, \ldots, x_n)$ - формула составленная из $x_1, \ldots, x_n$

$x_1, \ldots x_n$ будем называть логическими переменными этой формулы

Конъюктивным одночленом называется конъюкция переменных или их отрицаний. Дизъюктивный - аналогично.

ДНФ (дизъюктивная нормальная форма) формулы A называется равносильная ей формула, представляющая собой дизъюнкцию элементарных конъюкций.

КНФ (конъюктивная нормальная форма) - наоборот.

Всякая формула обладает обеими ДНФ и КНФ.

** Пример
$(A \uparrow B) \rightarrow \overline{(\overline{C} \rightarrow (B \lor C))}$


* Совершенность
ДНФ/КНФ называется совершенной, если
1) в каждую из элементарных дизъюнкций/конъюкций логическая переменная входит только один раз.
2) если логическая переменная входит в одну из элементарных дизъюнкций/конъюкций, то она входит и во все остальные.
3) Все элементарные дизъюнкции/конъюкции различны.

$(x \land y \land z) \lor (\overline{x} \land y \land z) \lor (x \land \overline{y} \land z)$ - СДНФ

Каждая не являющаяся тождественно ложной или истинной формула от n аргументов имеет единственную СДНФ/СКНФ.

** IDEA доказать

* Приведение к СНФ:
** Тождественные преобразования
*** Алгоритм
**** СКНФ
1. Найти КНФ
2. Путем добавления единичных противоречий $(a \land \neg{a})$ для недостающих переменных в отдельные слагаемые привести к СКНФ

**** СДНФ
1. Найти ДНФ
2. Путем добавления единичных тавтологий $(a \lor \neg{a})$ для недостающих переменных в отдельные множежители привести к СДНФ

** Таблица истинности
*** Алгоритм
**** СКНФ
1. Нужно выбрать все те значения переменных, когда формула ложна.
2. Для каждого набора выписываем элементарную дизъюнкцию. Переменная входит в нее сама если в этом наборе F иначе ее отрицание.
3. Образуем конъюнкцию всех дизъюнкций

**** СДНФ
1. Нужно выбрать все те значения переменных, когда формула истинна.
2. Для каждого набора выписываем элементарную конъюнкцию. Переменная входит в нее сама если в этом наборе T иначе ее отрицание.
3. Образуем дизъюнкцию всех конъюнкций

*** Пример
| x | y | z | F(x, y, z) |
|---+---+---+------------|
| 0 | 0 | 0 |          1 |
| 0 | 0 | 1 |          0 |
| 0 | 1 | 0 |          1 |
| 0 | 1 | 1 |          1 |
| 1 | 0 | 0 |          1 |
| 1 | 0 | 1 |          0 |
| 1 | 1 | 0 |          0 |
| 1 | 1 | 1 |          1 |

СДНФ -- $(\neg{x} \land \neg{y} \land \neg{z}) \lor (\neg{x} \land y \land \neg{z}) \lor \dots$

СКНФ -- $(x \lor y \lor \neg{z}) \land (\neg{x} \lor y \lor \neg{z}) \land (\neg{x} \lor \neg{y} \lor z)$

* Проблема разрешимости
** Критерий тождественной

** ...
Элементарная дизъюнкция тождественно истин

* Логическое следование
$A \rightarrow B \land B \rightarrow C \Rightarrow A \rightarrow C$

$H(x_1, \dots, x_n)$ называется логическим следствие формул. $F_1(x_1, \dots, x_n); \dots; F_m(x_1, \dots, x_n)$ если $H$ превращается в истинное выссказывания при всякой такой подстановке вместо ее переменных конкретных выссказываний, при которых формулы $F_1, \dots, F_n$ превращаются в истинные выссказывания.

Короче (математически не правильно) $H \Rightarrow F_1, \dots F_m$ обозначается $F_1, \dots, F_n \models H$

Из истинности посылок следует истинность вывода.

$F \models H \iff \models F \rightarrow H$ ($F \rightarrow H$ -- тавтология)

$\forall F_1, \dots, F_m, H : (F_1, \dots F_m \models H) \land (F_1 \land \dots \land F_m \models H) \land (\models (F_1 \land \dots \land \dots F_m ) \rightarrow H)$

** Свойства
1. $F_1, \dots, F_m \models F_i \Rightarrow$ для любого $i$
2. $F_1, \dots, f_m \models G_i | j \in 1,\dots,p; G_1, \dots, G_p \models H$, то $F_1, \dots F_m, \models H$

$F \equiv H \iff F \models H \land H \models F$

Если формула тавтология, то и ее любое следствие является тавтологией.
$\models F, F \models H \Rightarrow \models H$

** Правила логических умозаключений
$(\text{modus ponens}): \frac{F, F \rightarrow G}{G}$
$\models F, F \rightarrow G \Rightarrow \models G$

$(\text{modus tollens}): \frac{F \rightarrow G, \neg{G}}{\neg{F}}$
$\models \neg{G}, F \rightarrow G \Rightarrow \models \neg{F}$

** Проверка
$X \rightarrow (\neg{Y} \lor Z), \neg{X}, Y \rightarrow Z \models X \lor Z$

Алгоритм для находжения всех неравносильных формул которые являются логическими следствиями посылок
1. Составить конъюнкцию всех посылок
2. Найти СКНФ
3. Выписать все соверешенные одночлены и всевозможные конъюнкции этих одночленов

Получилась искомая формула.

В обратку:
Для следствия разные наборы посылок.

Чтобы найти все формулы логическим следствием каждой из которых будет данная формула (посылки), необходимо
1. Найти СКНФ данной формулы
2. Выявить все совершенные одночлены, которые в ней отсутствуют
3. Составить всевозможные конъюнкции из них
