:PROPERTIES:
:ID:       f305b0d5-9992-4d7d-b896-648a54bba14e
:END:
#+title: logic general
#+latex_class: article
#+latex_class_options: [letterpaper]
#+latex_header: \usepackage{fontspec}
#+latex_header: \setmainfont[Ligatures=TeX]{CMU Serif}
#+options: toc:t \n:t
#+lanugage: ru
#+latex_compiler: xelatex

* Цитаты
#+begin_quote
Умение отличать истинное от ложного, имеющее смысл от бессмыслицы и понятное от непонятного -- Успенский
#+end_quote

#+begin_quote
Если кто-то нашел ошибку в доказательстве, математик не имеет права настаивать на своем, а обязан поблагодарить за помощь и публично объявить о своей ошибке -- Непейвода
#+end_quote

#+begin_quote
Математик это портной, который шъёт всевозможные одежды ... -- Станислав Лем
#+end_quote

* Что такое мат. логика?
1) Наука об утверждениях
2) Формализовать
3) Доказательство

Просто логика используя математику

Логику интересует лишь форма наших мыслей, но не их содержание. Нам важна не дисемантика (смысл), а синтаксис.

#+begin_quote
Варкалось. Хливкие шорьки
    Пырялись по наве,
И хрюкотали зелюки,
    Как мюмзики в мове.
#+end_quote

* Определения
Логика -- это наука об анализе доказательств, аргументов и установлении принципов, на основании которых могут быть сделаны соответствующие рассуждения.

Доказательство -- это рациональный логический переход от принятой точки зрения (предпосылки), к тому рубежу, где ее необходимо доказать или подтвердить (вывод), осуществляемый при помощи рассуждений.

Предпосылка -- это утверждение, предназначенное для обоснования, доказание или объяснения некоторого аргумента.

Рассуждение -- получени новых знаний из предыдущих.

Выссказывание -- повествовательное предложение, которое можно отнести к верным или неверным утверждениям.
