:PROPERTIES:
:ID:       a3f75bd6-ef7d-429e-8b12-b524b822ff24
:END:
#+title: logic laws
#+latex_class: article
#+latex_class_options: [letterpaper]
#+latex_header: \usepackage{fontspec}
#+latex_header: \setmainfont[Ligatures=TeX]{CMU Serif}
#+options: toc:t \n:t
#+lanugage: ru
#+latex_compiler: xelatex

* 4 Закона логики
** Тождества
Любое рассуждение или мысль обязательно должна быть тождественна сама себе.
Критерии: Ясное, определенное, однозначным, не двусмысленным

*** Примеры
1) Например чем заканцивается день и ночь?
   Подмена понятия слово и время суток - софизм.
2) Студенты прослушали лекцию - пропустили или послушали? - двусмысленность.
3) Моему отцу столько же лет, сколько и мне. Отцом он стал только когда я родился.
   Подмена понятия человек и период жизни/стаж отца.
** Противоречия
Если одно суждение что-то утверждает, а другое отрицает об одном объекте в одно время и в одном отношении, то они не могут быть истинными одновременно.

*** Примеры
1) Он был молодой человек преклонного возраста
2) Миллионы лет Венера скрывала от глаз человечества - человечеству меньше
** Исключяющего третьего
Противоположные и противоречивые суждения

Если противоположные, то оба суждения могу быть истинными.
Если противоречивые, то одно - ложное, другое - истинное.

*** Примеры:
Либо выучил, либо не выучил. Даже если что-то написал.
Построить мост. Построил либо не построил.
** Достаточное основание
Каждое суждение может считаться достоверным, только в том случае, если оно было доказано.

*** Пример
Человек Н совершил преступление, поскольку он написал об этом сердечное признание.

Уборка выполнена != помещение выполнено
