:PROPERTIES:
:ID:       70371326-a03a-468d-a49b-6bb7116e97b3
:END:
#+title: logic set theory
#+date: [2024-09-09 Mon 09:04]
#+latex_class: article
#+latex_class_options: [letterpaper]
#+latex_header: \usepackage{fontspec}
#+latex_header: \setmainfont[Ligatures=TeX]{CMU Serif}
#+latex_header: \usepackage{bookmark}
#+latex_header: \usepackage{amssymb}
#+latex_header: \usepackage{amsmath}
#+latex_header: \setlength{\parindent}{0pt}
#+options: toc:t
#+lanugage: ru
#+latex_compiler: xelatex

* Contents :toc:noexport:
- [[#множество][Множество]]
  - [[#собственное-подмножество][Собственное подмножество]]
  - [[#что-то-там-с-морганом][Что-то там с морганом]]
  - [[#мощность][Мощность]]
  - [[#упорядоченные-пары-декартово-произведение][Упорядоченные пары (декартово произведение)]]
  - [[#характеристическая-функция][Характеристическая функция]]
- [[#теория-отношений][Теория отношений]]
  - [[#бинарное-отношение][Бинарное отношение]]
  - [[#свойства-отношений][Свойства отношений]]
  - [[#пример][Пример]]
  - [[#класс-эквивалентности][Класс эквивалентности]]
  - [[#порядок][Порядок]]
  - [[#отношение-соответствия][Отношение соответствия]]

* Множество
/Если чего-то нет, то смотри [[id:14934769-8e7e-4543-9c14-63ab9f792603][в матане]]/

понимается любое объединение в одно целое M определенных, вполне различаемых объектов m нашего восприятия или мысли. /по Канту/

В множестве на важен порядок записи элементов.

Множество - совокупность уникальных объектов.

$A = \{x: x \in Z \land x^2 + 4x = 12\} \iff A = \{-6; 2\}$

** Собственное подмножество
Собственное подмножество множества A называется множество B, если каждый его элемент является элементом множества A и можность A не равна можности B.

** Что-то там с морганом
$\neg{A \cup B} = \{x: x \notin (A \cup B)\}$
$\neg{A \cup B} = \{x: x \notin A \land x \notin B\}$

** Мощность
/cardinality/

Мощностью конечного множества S ($|S|$) называется количество его элементов.

*** Формула включений и исключений
\begin{equation}
\begin{aligned}
|A \cup B| = |A| + |B| - |A \cap B| \\
A = (A \backslash B) \cup (A \cap B) \\
B = (B \backslash A) \cup (A \cap B) \\
|A \backslash B| = m; |A \cap B| = n; |B \backslash A| = p; \\
|A \cup B| = m + n + p \\
= (m + n) + (n + p) - n \\
= |A| + |B| - |A \cap B|
\end{aligned}
\end{equation}

для трех множеств

\begin{equation}
|A \cup B \cup C| = |A| + |B| + |C| - |A \cap B| - |A \cap C| - |C \cap B| + |A \cap B \cap C|
\end{equation}

в общем виде

\begin{equation}
\begin{aligned}
|A_1 \cup \dots \cup A_n| = \sum_{i}^{} |A_i| - \sum_{i<j} |A_i \cap A_j| + \sum_{i<j<k} |A_i \cap A_j \cap A_k|
\end{aligned}
\end{equation}

*** Равмномощность и счетность
Два множества равномощные, если между ними можно установить взаимно однозанчаное соответствие при котором каждому элементу одного множества соответсвтует ровно 1 элемент другого.

Это подходит для бесконечных множеств. Например: [0; 1] равномощно [0; 2]

Счетное множество - множество равномощное множесту натуральных чисел.
Например $Z \textasciitilde N$, так как их можно упорядочить как: $\{0; 1; -1; 2; \dots\}$

Множество рациональных чисел счетно. $x \in Q \Rightarrow x = a / b; a \in Z; b \in N$
N - счетно, Z - счетно следовательно R представимо в виде объединения счетного числа счетных множеств.

Множество действительных чисел не является счетным.

$[0; 1] \textasciitilde$ множеству всех бесконечных последовательностей нулей и единиц.

*** Теорема Кантора-Рубенштейна
Поскольку любое число из этого отрезка можно записать в виде бесконечной двоичной дроби.

Если A равномощно некоторому подмножеству B и B равномощно некоторому подмножеству A, то A равномощно B.

Общая формулировка: никакое множество A не равномощну множеству всех своих подмножеств.

*** Вывод
Понятие множества не является непостредственно очевидным. (в связи с например парадоксом Рассела)

Если мы хотим рассуждать о множествах, не впадая в противоречия,
нужно проявлять осторожность на границах определения множеств всех множеств.

Безопасные правила обращения со множествами сформулированы в аксиоматической теории множеств.
- Формальная теория ZF (Цермело и Френкель)
- ZFC - с добавлением аксиомы выбора

В нашем курсе: Нельзя просто так рассмотреть множество всех множеств, т.к. класс потенциальных претендентов не обозрим.

** Упорядоченные пары (декартово произведение)
Декартово произведение произвольного числа множеств $A_1, A_2, ..., A_n$
является следующее множество $\{(a_1, a_2, ..., a_n): a_i \in A_i, i \in [1, 2, ..., n]\}$

Пример для двух множеств:
$A * B = {(a, b), a \in A, b \in B}$

Свойства элементов:
- Конечные
- Упорядоченные (порядок имеет значение) $\Rightarrow A * B \ne B * a \Rightarrow$ операция не коммунитативна.

$|S*K| = |S| \cdot |K|$

$A^n = A * A * ... * A$

** Характеристическая функция
Характеристической функцией (вектором) множества $B$ называет функцию $X_b$,
которая равна 1 на элементах B и 0 на других элементах.

\begin{equation}
\vec{X_b} = (x_1, x_2, ..., x_n) =
\begin{cases}
1, u_i \in B \\
0, u_i \notin B
\end{cases}
\end{equation}

\begin{equation}
\begin{aligned}
U = \{1, 2, 3, 4, 5, 6\} \\
B = \{3, 5\} \\
X_b = 0, 0, 1, 0, 1, 0
\end{aligned}
\end{equation}

* Теория отношений
** Бинарное отношение
Между множествами $A$ и $B$ называется множество $R \subset A * B$ иногда пишут $xRy, R - "x + y = 9"$.

Если $A = B$, то говорят об отношении $R$ на $A$

Отношение - $x + y = 9$
\begin{equation}
\begin{aligned}
A = \{1, 3, 5, 7\} \\
B = \{2, 4, 6\} \\
R = \{(x, y): x + y = 9\} \\
R \subset A * B \\
A * B = {(1; 2), (1; 4), ..., (7; 6)} \\
\end{aligned}
\end{equation}

** Свойства отношений
1) Рефлексивность: $xRx \forall x \in X$
2) Симметричность: $xRy \Rightarrow yRx \forall x \in X \forall y \in Y$
3) Транзитивность: $xRy \land yRz \Rightarrow xRz \forall x \in X \forall y \in Y \forall z \in Z$

Бинарное отношение R на множестве X называется отношением эквивалентности если выполнены все свойства.

** Пример
Есть множество студентов - $S$ и есть отношение $xRy = \{(x, y): \text{x - есть одногрупник y}; x,y \in S\}$

$\{(A, B); (C, D); (B, E)\}$
выполняется: 1, 2, 3

Мы можем разбить это множество на несколько множеств по признаку того в какой группе люди.

Если на множестве задано отношение эквивалентности, то все его элементы можно разбить на непересекающиеся подмножества.

*** Важно
Разбиение множества $X$ - совокупность непустых подмножеств $X_1, X_2, \dots, X_n$, такое что $X_1 \cup X_2 \cup \dots \cup X_n = X$ и $\forall X_i \forall X_j i \ne j: X_i \cap X_j = \emptyset$

** Класс эквивалентности
Класс эквивалентности $E_x$ - произвольного элемента $x \in X$
есть подмножество определяемое следующим множеством: $E_X = \{z \in X: zRx\}$

Совокупность классов эквивалентности элементов множества $X$ по отношению эквивалентности $R$ назвыается фактор-множество ($X_{/R}$).

** Порядок
Рефлексивное, транзитивное, но антисимметричное отношение $R$ на множестве $X$ называется частичным порядком.
Важен когда мы хотим показать старшинство (один элемент по какому то параметру превосходит другое).

Нессиметричность - нельзя точно сказать о симметрии.

Множества с частичным порядком принято называть частично упорядоченными множествами.

Линейным порядком на множестве X называется отношение частичного порядка,
при котором из любой пары элементов можно выделить предыдущий и последующий (пример: $\geq$).

** Отношение соответствия
Меджу элементами двух множеств
- Взаимно-однозначное соответствие (биективное отображение 1-1 $a = b$)
- Одно-многозначное (1-many $a = b^2$)
- Много-однозначное (many-1 $a^2 = b$)
- Много-многозначное (many-many $a \equiv 2 \mod n$)
