:PROPERTIES:
:ID:       bbcdfb12-2081-447d-9571-8c9fa188326e
:END:
#+title: analysis expression
#+latex_class: article
#+latex_class_options: [letterpaper]
#+latex_header: \usepackage{fontspec}
#+latex_header: \usepackage{bookmark}
#+latex_header: \setmainfont[Ligatures=TeX]{CMU Serif}
#+latex_header: \setlength{\parindent}{0pt}
#+options: toc:t
#+lanugage: ru
#+latex_compiler: xelatex

* Выссказывание
** Определение
Повествовательное предложение, которое можно отнести к верным или неверным утверждениям.

Обозначение - a, b, c

** Примеры
- Эта ручка синяя (правдивое выссказывание)
- Все студента специалитета -- кролики (ложное выссказывание)
- Слон большой (не выссказывание, потому что не понятно насколько большой и какой слон)

* Предикат
** Определение
Некоторое выражение (не обязательно математическое), зависящее от переменных, такое, что при подстановке в переменные некоторых значений, выражение становится выссказыванием.

Множество допустимых (например по условию задачи) значений -- область определения

Обозначение - A(x, y, ...), B(z, q, ...)

** Примеры
- "$a > 0$", $a \in Z$
- "x - Вася", x - человек
- "Все натуральные числа, заканчивающиеся на 0,2,4,6,8 - четные" - не предикат, потому что нет аргументов

* Операции с выссказыванием и предикатами
** Отрицание
*** Определение
Операция инвертирующая истинность выссказывания.

*В предложениях обычно применяется к глаголам/свойствам*
*** Примеры
- Доска на полу $\rightarrow$ Доска не на полу

  Доска - объект
  На полу - свойство

- Все студенты родились в 2008. $\rightarrow$ Не все студенты родились в 2008.

  /Что? Мы же говорили, что "не" применяется к свойствам?/

  В этом случае мы отрицаем "не все студенты", чтобы сохранить смысл. Нужно просто думать

  A = "x родился в 2008 году"

  $a = [\forall s \in M: A(s)]$
  $\neg{a} = [\exists s \in M: \neg{A(s)}]$

** Конъюнкция
Логическое И ($\land$)

** Дизъюнкция
Логическое ИЛИ ($\lor$)

** Импликация
Если А то Б ($\Rightarrow$)

| A | B | A $\rightarrow$ B |
|---+---+--------|
| 0 | 0 |      1 |
| 0 | 1 |      1 |
| 1 | 0 |      0 |
| 1 | 1 |      1 |

* Теорема
 Пусть a, b, c - выссказывания, тогда

1) $(a \land b) \land c = a \land (b \land c)$ -- сочетательный закон конъюнкции
2) $(a \lor b) \lor c = a \lor (b \lor c)$ -- сочетательный закон дизъюнкции
3) $a \land (c \lor b) = (a \land b) \lor (a \land c)$ -- распределительный закон конъюнкции относительно дизъюнкции
4) $a \lor (c \land b) = (a \lor b) \land (a \lor b)$ --
5) $a \land b = b \land a$ -- переместительный закон конъюнкции
6) $a \lor b = b \lor a$ -- переместительный закон дизъюнкции
7) $a \land (\neg{a}) = T$ -- закон исключения третьего
8) $\neg{(\neg{a})} = a$
9) $\neg{(a \land b)} = \neg{a} \lor \neg{b}$
10) $\neg{(a \lor b)} = \neg{a} \land \neg{b}$
11) $a \rightarrow b = \neg{a} \lor b$
12) $\neg{a \rightarrow b} = {a} \land \neg{b}$
13) $a \rightarrow b = \neg{a} \rightarrow \neg{b}$
